#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    # Configuración mapeos con anotaciones
    # resource: "@AppBundle/Controller/"
    # type:     annotation
    
    # Configuración yml
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:     /
