comments_new:
    path: /new
    defaults: {_controller: "AppBundle:Comment:new"}
    methods: POST
comments_delete:    
    path: /delete/{id}
    defaults: {_controller: "AppBundle:Comment:delete", id:null}
    methods: POST
comments_list:
    path: /list/{id}
    defaults: {_controller: "AppBundle:Comment:list", id:null}
    methods: GET