users_new:
    path: /new
    defaults: {_controller: "AppBundle:User:new"}
    methods: POST
users_edit:
    path: /edit
    defaults: {_controller: "AppBundle:User:edit"}
    methods: POST
users_upload_image:
    path: /upload-image
    defaults: {_controller: "AppBundle:User:uploadImage"}
    methods: POST