videos_pruebas:
    path: /pruebas
    defaults: {_controller: "AppBundle:Video:pruebas"}
    methods: POST
videos_new:
    path: /new
    defaults: {_controller: "AppBundle:Video:new"}
    methods: POST
videos_edit:
    path: /edit/{id}
    defaults: {_controller: "AppBundle:Video:edit", id:null}
    methods: POST