app_default:
    # Importamos otras confgiuraciones
    resource: "@AppBundle/Resources/config/routing/default.yml" 
    prefix: /
    
app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml" 
    prefix: /users

app_videos:
    resource: "@AppBundle/Resources/config/routing/videos.yml" 
    prefix: /videos
